# Generated by Django 4.1.1 on 2022-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposalrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2021-7-4', verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
