# Generated by Django 4.1.1 on 2022-09-10 14:20

import app.utils
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Картинка (svg)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('custom_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('instruction', models.FileField(blank=True, null=True, upload_to='', verbose_name='Инструкция по установке')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('patina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Патина')),
                ('made_in', models.CharField(blank=True, max_length=50, null=True, verbose_name='Производство')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to=app.utils.save_collections_image, verbose_name='Картинка')),
                ('bed_size', models.CharField(blank=True, help_text='Пример формата: 60x140x34 см.', max_length=50, null=True, verbose_name='Кровать (ДxШxВ)')),
                ('drawer_size', models.CharField(blank=True, help_text='Пример формата: 60x140x34 см.', max_length=50, null=True, verbose_name='Комод (ДxШxВ)')),
                ('wardrobe_size', models.CharField(blank=True, help_text='Пример формата: 60x140x34 см.', max_length=50, null=True, verbose_name='Шкаф (ДxШxВ)')),
                ('custom_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'комплект',
                'verbose_name_plural': 'Комплекты',
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='CustomSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('custom_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'кастомная характеристика',
                'verbose_name_plural': 'Кастомные характеристики',
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('instruction', models.FileField(blank=True, null=True, upload_to='', verbose_name='Инструкция по установке')),
                ('material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('patina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Патина')),
                ('made_in', models.CharField(blank=True, max_length=50, null=True, verbose_name='Производство')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('size', models.CharField(blank=True, help_text='Пример формата: 60x140x34 см.', max_length=50, null=True, verbose_name='Размеры ДxШxВ')),
                ('custom_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collection', verbose_name='Комплект')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-custom_order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'Слайдер',
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.utils.save_products_image, verbose_name='Картинка')),
                ('is_main_image', models.BooleanField(default=True, verbose_name='Главная картинка?')),
                ('custom_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalSpecificationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('custom_order', models.PositiveIntegerField(default=0)),
                ('custom_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customspecification', verbose_name='Характеристика')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_product', to='app.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'дополнительные характеристики',
                'verbose_name_plural': 'Дополнительные характеристики',
                'ordering': ['custom_order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalSpecificationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('custom_order', models.PositiveIntegerField(default=0)),
                ('custom_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customspecification', verbose_name='Характеристика')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_collection', to='app.collection', verbose_name='Комплект')),
            ],
            options={
                'verbose_name': 'дополнительные характеристики',
                'verbose_name_plural': 'Дополнительные характеристики',
                'ordering': ['custom_order'],
            },
        ),
    ]
