# Generated by Django 4.1.1 on 2022-09-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_main_image',
        ),
        migrations.AlterField(
            model_name='additionalspecificationcollection',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
        migrations.AlterField(
            model_name='additionalspecificationcollection',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_specifications_collection', to='app.collection', verbose_name='Комплект'),
        ),
        migrations.AlterField(
            model_name='additionalspecificationproduct',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
        migrations.AlterField(
            model_name='additionalspecificationproduct',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_specifications_product', to='app.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='category',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
        migrations.AlterField(
            model_name='customspecification',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Кастомный порядок'),
        ),
    ]
