# Generated by Django 4.1.1 on 2022-09-10 17:42

import app.utils.save_image_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_productimage_is_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_2',
            field=models.ImageField(default=1, upload_to=app.utils.save_image_settings.save_collections_image, verbose_name='Картинка для главной'),
            preserve_default=False,
        ),
    ]
