# Generated by Django 4.1.1 on 2022-09-10 21:18

import app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_collection_image_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[app.utils.validators.only_int], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=32, verbose_name='Email')),
                ('vk', models.URLField(verbose_name='Ссылка на ВК')),
                ('telegram', models.URLField(verbose_name='Ссылка на Telegram')),
                ('youtube', models.URLField(verbose_name='Ссылка на YouTube')),
            ],
            options={
                'verbose_name': 'данные сайта',
                'verbose_name_plural': 'Данные сайта',
            },
        ),
    ]
