# Generated by Django 4.1.1 on 2022-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_websiteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='logo',
            field=models.ImageField(default='images/logo.png', upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram'),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на ВК'),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
