# Generated by Django 4.1.1 on 2022-09-11 09:30

import app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_websiteinfo_logo_alter_websiteinfo_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[app.utils.validators.only_int], verbose_name='Телефон'),
        ),
    ]
